---

- name: установка пакетов для war сервера
  hosts: war
  become: yes

  tasks:
  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
      update_cache: yes

  - name: Ensure tomcat  package is present
    apt:
      name: tomcat9
      state: present

  - name: Ensure java  package is present
    apt:
      name: default-jdk
      state: present

  - name: Ensure maven package is present
    apt:
      name: maven
      state: present

  - name: Ensure git  package is present
    apt:
      name: git
      state: present

  - name: Clone repo
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /home/lab1
      version: master

  - name: maven package
    shell: mvn package
    args:
      chdir: /home/lab1
 
  - name: Copy war
    copy:
      src: /home/lab1/target/hello-1.0.war
      dest: /var/lib/tomcat9/webapps
      remote_src: yes
  
  - name: Restart tomcat9
    service:
      name: tomcat9
      state: restarted

  - name: копируем с war на мастер
    fetch:
      src: /home/lab1/target/hello-1.0.war
      dest: /tmp/   
      flat: yes
 
- name: установка пакетов для prod сервера
  hosts: prod
  become: yes

  tasks:
  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
      update_cache: yes

  - name: Ensure tomcat  package is present
    apt:
      name: tomcat9
      state: present

  - name: Ensure java  package is present
    apt:
      name: default-jdk
      state: present

  - name: Копируем с мастер на prod
    copy:
      src: /tmp/hello-1.0.war
      dest: /var/lib/tomcat9/webapps

  - name: Restart tomcat9
    service:
      name: tomcat9
      state: restarted


